version: '3.9'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile.api
    container_name: ocr_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ~/.aws:/root/.aws  # Para que el contenedor acceda a tus credenciales
    depends_on:
      - db
    env_file:
      - .env  # ← carga las variables del archivo .env

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    container_name: ocr_web
    ports:
      - "5050:5000"
    volumes:
      - ./web:/web
    depends_on:
      - api

  ai_models:
      build:
        context: ./ai_models
        dockerfile: Dockerfile.ai_models
      container_name: ocr_ai_models
      ports:
        - "8080:8080"
      volumes:
        - ./ai_models:/app
        - ./models:/app/models  # Aquí colocarás tu modelo Hugging Face descargado
      environment:
        - TRANSFORMERS_CACHE=/app/models

  db:
    image: postgres:15
    container_name: ocr_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ocrdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: