# version: '3.9'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile.api
    container_name: ocr_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - .env  # ← carga las variables del archivo .env
    restart: unless-stopped

  db_viewer:
    image: sosedoff/pgweb
    container_name: ocr_db_viewer
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/ocrdata?sslmode=disable
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    container_name: ocr_web
    ports:
      - "5050:5000"
    volumes:
      - ./web:/web
    depends_on:
      - api
    restart: unless-stopped


  db:
    image: postgres:15
    container_name: ocr_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ocrdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
