# web/Dockerfile.web
FROM python:3.11-slim

WORKDIR /web

# Instalar dependencias
RUN pip install --upgrade pip && \
    pip install --no-cache-dir flask requests sqlalchemy psycopg2-binary

# Exponer puerto de Flask
EXPOSE 5000

CMD ["python", "app.py", "--reload"]
