# web/Dockerfile.web
FROM python:3.11-slim

WORKDIR /web

# Copiar código fuente de la interfaz web
COPY . .

# Instalar dependencias
RUN pip install --upgrade pip && \
    pip install --no-cache-dir flask requests sqlalchemy psycopg2-binary

# Exponer puerto de Flask
EXPOSE 5000

CMD ["python", "app.py"]
